Модель рекуррентной сети с цепью нейросетевых моделей долгой кратковременной памяти 

In [62]:
import os
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf


In [63]:
seq_len = 10

In [64]:
data = [[float(i)] for i in range(10**3)]
#data = [data[i:i+seq_len] for i in range(len(data)-32)]
target = [float(i) for i in range(seq_len,10**3)]

In [65]:
data = [[float((-1)**i)+1] for i in range(10**3)]
#data = [data[i:i+seq_len] for i in range(len(data)-32)]
target = [float((-1)**i+1) for i in range(seq_len,10**3)]

In [66]:
train = tf.keras.utils.timeseries_dataset_from_array(
      data=data,
      targets=target,
      sequence_length=seq_len,
      batch_size=1,)

In [67]:
for j,i in enumerate(train):
    print(i)
    break
    

(<tf.Tensor: shape=(1, 10, 1), dtype=float32, numpy=
array([[[2.],
        [0.],
        [2.],
        [0.],
        [2.],
        [0.],
        [2.],
        [0.],
        [2.],
        [0.]]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>)


In [68]:
lstm_model = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(10, return_sequences=False),
    
    tf.keras.layers.Dense(units=1)
])

In [69]:
def compile_and_fit(model, train, val = None):
    '''early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss',
                                                    patience=patience,
                                                    mode='min')'''

    model.compile(loss=tf.losses.MeanSquaredError(),
                optimizer=tf.optimizers.SGD(learning_rate=0.01),
                metrics=[tf.metrics.MeanAbsoluteError()])

    history = model.fit(train,
                      validation_data=val,
                      )
    return history

In [70]:
hist = compile_and_fit(lstm_model, train)

990/990 [==============================] - 6s 4ms/step - loss: 0.2659 - mean_absolute_error: 0.3562


In [72]:
for j,i in enumerate(train):
    print(i)
    print(lstm_model.predict(i))
    if j==1:
        break

(<tf.Tensor: shape=(1, 10, 1), dtype=float32, numpy=
array([[[2.],
        [0.],
        [2.],
        [0.],
        [2.],
        [0.],
        [2.],
        [0.],
        [2.],
        [0.]]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>)
1/1 [==============================] - 0s 16ms/step
[[1.9951148]]
(<tf.Tensor: shape=(1, 10, 1), dtype=float32, numpy=
array([[[0.],
        [2.],
        [0.],
        [2.],
        [0.],
        [2.],
        [0.],
        [2.],
        [0.],
        [2.]]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>)
1/1 [==============================] - 0s 22ms/step
[[0.00439066]]
